config/routes.rb
Blog2::Application.routes.draw do
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  resources :posts
  get "home/index"

    root :to => "home#index"  

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :name,  :presence => true,
                    :length => {:minimum => 1, :maximum => 100}
    validates :context, :presence => true,
                    :length => { :minimum => 1, :maximum => 1000000}
    validates :title, :presence => true,
                  :length => { :minimum => 1 , :maximum => 100}
    self.per_page = 10;
    
    #search functionality
    def self.search(search, page)
      paginate :per_page => 10, :page => page,
           :conditions => ['name like ? OR context like?', "%#{search}%", "%#{search}%"], :order => '6 DESC'
    end
    
end

app/models/tags.rb
class Tags < ActiveRecord::Base
end

app/models/tags_posts.rb
class TagsPosts < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  
  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'])
    
end

end

class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end
  
  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #@@p_page = 10
  #@@page = 1
  #@@cur_end = @@p_page*@@page;
  #@@cur_start = @@p_page*@@page-@@p_page;
  
  # GET /posts
  # GET /posts.xml
  def index
    #@posts = Post.find(:all, :conditions => {:id => udr_start(@@p_page,@@page)..udr_end(@@p_page,@@page)}, :order => '6 desc')
    #@posts = Post.all(:order => '6 desc')
    #@posts = Post.paginate(:page => params[:page], :order => '6 DESC')
    @posts = Post.search(params[:search], params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  def searcher
    @posts = Post.search(params[:search], params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # def prev
  #   if @@page > 1
  #    @@page -= 1
  #  end
  #  respond_to do |format|
  #    format.html { redirect_to(@posts) }
   #   format.xml  { render :xml => @posts }
  # end
  # end

  # def next
 #   @@page += 1
# respond_to do |format|
   #   format.html { redirect_to(@posts)}
  #    format.xml  { render :xml => @posts }
      #  end
      #  end

  # PUT /posts/1
  # PUT /posts/1.xml  
  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
  #protected
  # def udr_start(p_page,page)
  #  return (p_page*page)-p_page
  # end
  
  #def udr_end(p_page, page)
 #   return p_page*page
#end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  auth = request.env['rack.auth']
  unless @auth = Authorization.find_from_hash(auth)
    # Create a new user or add an auth to existing user, depending on
    # whether there is already a user signed in.
    @auth = Authorization.create_from_hash(auth, current_user)
  end
  # Log the authorizing user in.
  self.current_user = @auth.user

  render :text => "Welcome, #{current_user.name}."

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Home English Home</h1>
<br>
<%= link_to 'Blog', posts_path %>
</br>
<br>
<%= link_to 'CE Capstone', 'https://sites.google.com/site/189bits/', :confirm => "Are you sure?"%>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!--><p class="notice"><%= notice %></p><-->
  <!--><p class="alert"><%= alert %></p><-->
</head>
<body style="background: #CCCCCC;">

<%= yield %>

</body>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title,  :rows => 6 %>
  </div>  
  <div class="field">
    <%= f.label :context %><br />
    <%= f.text_area :context, :rows => 6 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="post_list">
<CENTER><h1>Posts</h1></CENTER>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Last Update</th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >
    <td><%= post.name %></td>
    <td><%= link_to post.title, post %></td>
    <td><%= post.updated_at%></td>
    <p>
    	<td><%= link_to 'Edit', edit_post_path(post) %></td>
   	 	<td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
	  </p>
 </tr>
<% end %>
</table>

<%= will_paginate @posts, :page_links => true %>
<% form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search term:
    <%= text_field_tag :search, params[:search] %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/searcher.html.erb
<CENTER><h1>Listing searches</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Last Update</th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= link_to post.title, post %></td>
    <td><%= post.updated_at%></td>
    <p>
    	<td><%= link_to 'Edit', edit_post_path(post) %></td>
   	 	<td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
	  </p>
  </tr>
<% end %>
</table>
<%= will_paginate @posts, :page_links => true %>

</CENTER>

<%= link_to 'New Post', new_post_path %>
<br>
<%= link_to 'Home', home_index_path %>
</br>
<%= link_to 'Back to Posts', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Context:</b>
  <%= @post.context %>
</p>

<p>
  <b>Date Posted:</b>
  <%= @post.updated_at %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>